### ISSUE TITLE
Would be helpful to tag your images..

### ISSUE THREAD

**Issue by callowaylc** [kannix/monero-full-node#12]
.. before introducing breaking changes. 

kannix/monero-full-node:2.0.0-afterbreakingchange

**Comment by kannix** [comment]
I am sorry for any inconvenience with using the latest version. However I don't think that versioning would help with this. I have no time for supporting two versions (e.g. one with running as root and another with an monero user). If you wanted to run the node after the hard fork your only choice is to use the latest image..

**Comment by callowaylc** [comment]
dude, its not about supporting two versions, its about providing images that are reflective of the repository (from which the image is built) at given state-in-time; i have no beef with the choice to move to the monero user - its your project, go nuts, but tagging your images with the a git short sha would go a long way. 

This is the last commit, prior to the breaking change:
https://github.com/kannix/monero-full-node/commit/855f95534b28f9a2ce8945cf80607230391a034c

Any docker image that I build, regardless of whether its run through an orchestration pipeline, or done manually, I would at least do something like the following. 

```bash
$ sha=`git rev-parse --short` 
$ docker tag $image:latest $image:`git rev-parse --short $sha`
$ docker push $image:$sha 
```

Now, when my entire monero pipeline goes fubar, after the latest (pun intended) kannix/full-node breaks, I can redeploy on a given sha.
