### ISSUE TITLE
Synology Docker trouble

### ISSUE THREAD

**Issue by oldgeezy** [kannix/monero-full-node#13]
I'm not able to get this working on my Synology.  Followed the instructions but it's still running into the permissions error and crashing repeatedly.  Same issue with another docker container by Etix.  Is there some step required on the host to make this work?  I'm lost here.  Other linuxserver.io containers make use of PUID and PGID environment variables.  Would that help?

**Comment by kannix** [comment]
I am sorry but I don't own a Synology NAS so my debug capabilities are very limited.
I have heard from an user that he is running this container on his Synology. So the only thing I know is that it should work. 

Regarding the PUID and PGIG I guess its not necessary. 

I would try to run the container as root with bash to debug the permissions of the mounted volume e.g. (out of my head) `docker run -v xmrchain:/home/monero/.bitmonero -t --rm --name=monerod -u root --entrypoint=/bin/bash kannix/monero-full-node` in that bash you could try to look up the permissions of `/home/monero/.bitmonero` and maybe try to switch to the monero user and check if you could create files/directories in that location

**Comment by cryptoquick** [comment]
Just ran into this today. Pretty easy fix:
1. ssh into the DiskStation
2. when you configured the container, you should have set up `/home/monero/.bitmonero` to point to a directory on your volume, so cd to that directory
3. sudo chown 1000 `that directory`
