### ISSUE TITLE
support testnet

### ISSUE THREAD

**Issue by binlaniua** [kannix/monero-full-node#21]
how to start testnet, change entrypoint ?

**Comment by kannix** [comment]
I haven't tried it but it should be sufficient to change the CMD e.g. like this:
`docker run -tid --restart=always -v xmrchain:/home/monero/.bitmonero -p 18080:18080 -p 18081:18081 --name=monerod kannix/monero-full-node --non-interactive --restricted-rpc --rpc-bind-ip=0.0.0.0 --confirm-external-bind --testnet`

there is no need to change the entrypoint or anything in the docker image

**Comment by binlaniua** [comment]
thanks
