### ISSUE TITLE
monero-wallet-cli

### ISSUE THREAD

**Issue by kilo42L** [kannix/monero-full-node#22]
Is there a way to run monero-wallet-cli or to mine from this container. I am wanting both if possible.
Thanks

**Comment by kannix** [comment]
No, this container is only for the node.. for mining i have a different container based on xmrig: https://github.com/kannix/monero-miner

if you want to include the wallet-cli feel free to fork my container. I want to keep this as lean as possible and do only one thing "running a node"

**Comment by kilo42L** [comment]
Thank you, do you have one for rpc or is that included in the miner?

**Comment by kannix** [comment]
The deamon has a rpc interface that can be used.. the miner doesn't have one.. but why would you need one?

**Comment by kilo42L** [comment]
I wanted to setup to use RPC payments but I don't see any of the binaries on the node even for rpc. Then mine from the monorod daemon.
Maybe I'm going about it wrong but of you could share with me how this would be possible I'd appreciate it. Thanks
Tommy

February 20, 2020 8:27 AM, "Basti" <notifications@github.com (mailto:notifications@github.com?to=%22Basti%22%20<notifications@github.com>)> wrote:
	The deamon has a rpc interface that can be used.. the miner doesn't have one.. but why would you need one?
