### ISSUE TITLE
Is --net=host really required?

### ISSUE THREAD

**Issue by IronicBadger** [kannix/monero-full-node#7]
Any reason I couldn't just expose the ports from the Dockerfile instead of net=host?

**Comment by kannix** [comment]
Not at all.. explicit mapping these ports to the host is definitely the better/preferred way of using this image 👍 i will update the example

**Comment by IronicBadger** [comment]
Great! Whilst I have you, the daemon starts up and seems to exit immediately when not run in interactive mode. I want the container to run detached...
