### ISSUE TITLE
Incoming connections

### ISSUE THREAD

**Issue by keatond** [kannix/monero-full-node#8]
Good Morning Kannix!

I am really not sure if this is an issue but wanted to see if you possibly might know how to fix the issue that is occurring when I am running the docker image. I am trying to run an open node for the community. I am trying to run on port 18089(router port is forwarded), I am binding to ip 0.0.0.0). When i go to the terminal and type "Status" it will not show any incoming connections. I am also able to connect using the Monero GUI from work on my laptop.

I am really not sure why incoming connections stays at 0.

**Comment by kannix** [comment]
Did I understand you correctly that the node is fully functional (e.g. you can connect from your work laptop and the wallet syncs successfully?) and the "only" problem is that the stats output never shows anything else than 0 ?

**Comment by keatond** [comment]
Yes you are correct, I'm not sure if it is accessible by others or not. It
has been up for 3 days now but incoming connections still says 0. Normally
when I run the node on a Windows machine I will have incoming connections
within minutes. I'm just trying to make sure it would be seen by websites
like Moneroworld that scan for open nodes on 18089.

Thanks for any help!

**Comment by kannix** [comment]
Just ran the latest version of this image, synced the full blockchain and looked up the output of `./monderod status` and it shows me `Height: 1557822/1557822 (100.0%) on mainnet, mining info unavailable, net hash 501.68 MH/s, v7, up to date, 8(out)+17(in) connections, uptime 0d 2h 15m 15s`

so its definitely no problem of this docker image.

I guess it's related to some NAT (port forwarding problems) but unfortunately I have no good idea on how to help you out with this.

**Comment by keatond** [comment]
Hey Kannix!

Thanks for testing it out and narrowing it down to something in my set up. I'll try something different things to get it working. What port were you running on when you grabbed the output of status?

**Comment by kannix** [comment]
> What port were you running on when you grabbed the output of status?

good point, forget about that test! i used the default ports.. 

another test with running the image like this ` docker run -v xmrchain:/root/.bitmonero -td --restart=always -p 18089:18089 --name=monerod kannix/monero-full-node --restricted-rpc --rpc-bind-ip=0.0.0.0 --confirm-external-bind --p2p-bind-port=18089` seems to work.. after a few minutes i had 8 out and 3 in connections.. 

so i guess the trick is to tell monerod the alternative port in its parameters.. just mapping the 18080 port by docker to 18089 on the host is not enough..
